#------------------------------------------------------------------------------
# TravisCI configuration file for IMA.
#
# The documentation for IMA is hosted at http://skalelabs.org
#
# ------------------------------------------------------------------------------
# This file is part of IMA.
#
# IMA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IMA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IMA.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2019 IMA contributors.
#------------------------------------------------------------------------------

language: node_js
node_js:
  - "10"
os: linux
dist: bionic
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
jobs:
    include:
        - stage: test
          install:
            - pip3 install slither-analyzer
            - cd proxy
            - bash ./scripts/copy.sh
            - yarn install
            - npx buidler --version

            - cd ../agent 
            - npm install
            
            - cd ../npms/skale-ima
            - npm install

            - cd ../../proxy
          before_script:
            - npx ganache-cli --gasLimit 8000000 --quiet --acctKeys ../test/accounts.json &
          script:
            - yarn lint || travis_terminate 1
            - slither --version
            - slither . --filter-path openzeppelin-solidity,@openzeppelin/contracts/ || true            
            - slither . --filter-path openzeppelin-solidity,@openzeppelin/contracts/ --exclude-informational --exclude reentrancy-events,constant-function,calls-loop,reentrancy-benign,pragma,assembly,blank-lines,timestamp,external-function,constable-states,locked-ether,solc-version,too-many-digits,shadowing-state,shadowing-local,uninitialized-state || travis_terminate 7
            - yarn tslint || travis_terminate 2            
            - yarn generate
            - bash ./scripts/remove.sh
            - RUNNING_NETWORK=test bash ./scripts/prepareSkaleManagerComponents.sh
            - yarn test || travis_terminate 3
            - cd ../test
            - python3 ../scripts/config_from_accounts.py accounts.json config.json
            - pip3 install -r requirements.txt
            - python3 test.py || travis_terminate 6
          after_script:
            - cd ../proxy
            - npx buidler coverage --solcoverjs .solcover.js || travis_terminate 4
            - cat coverage/lcov.info | npx codecov
            - cd ..

        - stage: deploy
          if: branch IN (master, release-candidate, develop, beta)
          script:
            - export VERSION=$(cat VERSION)
            - export VERSION=$( (test $TRAVIS_BRANCH = "master" && echo $VERSION) ||
                                (test $TRAVIS_BRANCH = "release-candidate" && ./calculate_version.sh rc $VERSION) ||
                                ./calculate_version.sh develop $VERSION)
            - echo "Version $VERSION"
            - (test $TRAVIS_BRANCH = "master" && export RELEASE=true) || true
            - ./build_image.sh || travis_terminate 5

          before_deploy:
            # Set up git user name and tag this commit
            - (
              test ! $TRAVIS_TAG &&
              git config --local user.name "skale-jenkins" &&
              git config --local user.email "$GITHUB_EMAIL" &&
              export TRAVIS_TAG=v$VERSION &&
              git tag "$TRAVIS_TAG" &&
              git push https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG
              ) || true
            - export SKIP_BUILD=true
          deploy:
            - provider: releases
              api_key: "$GITHUB_OAUTH_TOKEN"
              skip_cleanup: true
              on:
                  repo: $TRAVIS_REPO_SLUG
                  branch: master
            - provider: releases
              api_key: "$GITHUB_OAUTH_TOKEN"
              skip_cleanup: true
              prerelease: true
              on:
                repo: $TRAVIS_REPO_SLUG
                branch: release-candidate
            - provider: script
              script: bash ./build_image.sh $DOCKER_USERNAME $DOCKER_PASSWORD
              on:
                repo: $TRAVIS_REPO_SLUG
                branch:
                    - master
                    - release-candidate
                    - develop
                    - beta
